### ISSUE TITLE
Ability to add tooltip to Header item

### ISSUE THREAD

**Issue by richpixel** [mbrn/material-table#1263]
Is it currently possible to add a tooltip to items in the header? If it isn't possible I was considering injecting a tooltip by locating the item from an id for the item, but I also don't see a way to add a specific id to the <th> element.

Thanks

**Comment by twhetzel** [comment]
I thought there was a parameter to do this, but haven't come across it again in the docs. I did a very bulky, pure CSS implementation as:
```
title: <div className="tooltip">Metadata Status
<span className="tooltiptext">Validation status of the template metadata.</span></div>
```
And then CSS from here: https://www.w3schools.com/css/css_tooltip.asp

I'm looking to find a better way to do this.

**Comment by miktap** [comment]
Column `title` property type is actually `string | ReactElement` (documentation at the moment says it's `string` only) so you can also override title to use React Tooltip, e.g.:

```typescript
  import { Tooltip, TableCell } from '@material-ui/core';

  const createHeaderWithTooltip = (title: string, tooltip: string) => {
    return (
      <Tooltip title={tooltip} placement='top'>
        <TableCell>{title}</TableCell>
      </Tooltip>
    );
  };

  const [columns, setColumns] = React.useState<Array<Column<Data>>>([
    { title: createHeaderWithTooltip('Name', 'Name of the data'), field: 'name' },
  ]);
```

**Comment by miktap** [comment]
Setting `ReactElement` as a `title` does have drawbacks. The `title` is for example used as a `placeholder` property for a textfield or currency field when adding/editing a field. And the `placeholder` property only supports strings.

**Comment by jakeleventhal** [comment]
Something similar to this could look good
<img width="328" alt="Screen Shot 2019-12-25 at 11 17 09 AM" src="https://user-images.githubusercontent.com/15133828/71449733-214ae700-2708-11ea-9c27-a4fd7019871e.png">

**Comment by jakeleventhal** [comment]
The tooltip appears to show up in the middle of the table here? I think something may be wrong. Can we reopen this
<img width="1669" alt="Screen Shot 2020-01-25 at 3 36 28 PM" src="https://user-images.githubusercontent.com/15133828/73128731-94a27b80-3f88-11ea-97a0-c156450654a9.png">

**Comment by mbrn** [comment]
Hi @jakeleventhal ,

I will take a look again.

**Comment by jakeleventhal** [comment]
Also, there should be some sort of indication that the header has a tooltip. Right now, it is not clear until it appears

**Comment by jakeleventhal** [comment]
not stale @mbrn

**Comment by mbrn** [comment]
Problem solved with 1.68.1

**Comment by soumyaDivami** [comment]
@mbrn I am using v 1.69 and still have this issue. It should be right below right? 
![image](https://user-images.githubusercontent.com/65209523/99368093-c5b9b700-28e0-11eb-9b86-c5eb71ac4dbe.png)

**Comment by aguessous** [comment]
hi
const getTooltip= () => {
    return <div>Hello <br /> world </div>;

  const [columns, setColumns] = useState<any[]>([
    { title: 'my title', field: 'name', tooltip: getTooltip() },
  ]);
