### ISSUE TITLE
CSV export breaks with "#" in data

### ISSUE THREAD

**Issue by rbeers** [mbrn/material-table#286]
Any data that contains "#" breaks the csv export.    Using chrome browser.  I assume # is being used as a break in the data structure.  Is there any way to specify another break character or handle the case for # symbol?

**Comment by mbrn** [comment]
Hi @rbeers ,

This bug is about https://github.com/mbrn/filefy . It is my project too. I will look at it asap.

**Comment by mbrn** [comment]
Hi @rbeers ,

Which version do you use?

If you use latest version of material-table. We already fixed this problem. but you should remove node_modules and package-lock.json(or yarn). Then npm install every dependency again.

Because we fixed this problem with filefy@1.7.0 and upgrade material-table to it. Your project may use filefy@1.6.0 still. Please check it.

**Comment by rbeers** [comment]
I upgraded to the latest version of material-table, removed node_modules and all lock files, re-installed, and verified filefy@0.1.7 in dependency tree.  The problem still persists for me.  Here is the example I'm using

```jsx
 <MaterialTable
    columns={[
      { title: 'Adı', field: 'name' },
      { title: 'Soyadı', field: 'surname' },
      { title: 'Doğum Yılı', field: 'birthYear', type: 'numeric' },
      {
        title: 'Doğum Yeri',
        field: 'birthCity',
        lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
      },
    ]}
    data={[
      { name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63 },
      { name: 'Rob', surname: 'Beers #', birthYear: 1987, birthCity: 63 },
      { name: 'Test', surname: 'User', birthYear: 1987, birthCity: 63 },
    ]}
    title="Demo Title"
    options={{
      exportButton: true,
    }}
  />
```

CSV exported:
```csv
<U+FEFF>"Adı","Soyadı","Doğum Yılı","Doğum Yeri"
"Mehmet","Baran",1987,63
"Rob","Beers
```

Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by rbeers** [comment]
For solution: see https://github.com/mbrn/filefy/issues/10
