### ISSUE TITLE
Failed to parse source map from "DoubleScrollbar.js.map" file: Error ENOENT: no such file or directory open 'DoubleScrollbar.js.map'

### ISSUE THREAD

**Issue by tytom2003** [mbrn/material-table#3170]
when i add import MaterialTable from 'material-table', it will show below error.

WARNING in ./node_modules/react-double-scrollbar/dist/DoubleScrollbar.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'D:\reactjs\crudtable\node_modules\react-double-scrollbar\dist\DoubleScrollbar.js.map' file: Error: ENOENT: no such file or directory, open 'D:\reactjs\crudtable\node_modules\react-double-scrollbar\dist\DoubleScrollbar.js.map'.

OS: windows 10 64bit
Nodejs: 16.16.0 
Material-Table:  2.0.3
material-ui/core: ^4.12.4
material-ui/icons: ^4.11.3
material-ui/lab: ^4.0.0-alpha.61
react-double-scrollbar: ^0.0.15

**Comment by leungk712** [comment]
I am using material-table core and came across this issue. Are you using `react-scripts: >5.0.0`? If so it's tied to this: https://github.com/facebook/create-react-app/discussions/11767

Seems the current solution is to add `GENERATE_SOURCEMAP=false` to your `.env` file

**Comment by huda23aduh** [comment]
i am also facing this issue

**Comment by fidel037** [comment]
is someone going to fix this?

**Comment by AppointMike** [comment]
What was the fix for this. I started getting this randomly

**Comment by donavan-tangible** [comment]
Consider to use this fork until a the fix is merged

package.json:
...
"dependencies": {
    "react-double-scrollbar": "https://github.com/IniterWorker/react-double-scrollbar.git",
}

**Comment by AyeshW** [comment]
I'm getting exactly the same issue.

**Comment by WoodyLiCHT** [comment]
It is disappointing that in 2024, this issue remains unresolved.

**Comment by HongJheLi** [comment]
It is disappointing that in 2024, this issue remains unresolved.
