### ISSUE TITLE
Search doesnt include columns with custom `render`

### ISSUE THREAD

**Issue by DmitryNefedov** [mbrn/material-table#67]
**Describe the bug**
Using column with custom `render` function exclude it from search.

**To Reproduce**
1. Use columns with `render` for id
2. Search by partial id

**Expected behavior**
Search results show columns with matching id

**Actual behaviour**
Search cant use columns with render

**Additional context**
E.g. columns
```
  const columns = [
    {title: 'Some Id', render: renderSomeId, field: 'some_id'},
...
];

...

const renderSomeId = (row) => {
    <Link to={someUrl + row.some_id}>
          {row.some_id}
        </Link>

}
```
As a result, we have links with id text shown. If we have ids like abc123, abc234, test000 we would expect that search for `abc` would show first 2 rows; however, "no results" shown.

**Comment by mbrn** [comment]
Hi @DmitryNefedov,

I will do this feature asap

**Comment by mbrn** [comment]
@DmitryNefedov ,

I change search to run on field value of every column. Not on render result. Because render result is a React.Element and it is not searchable. if you want to make  a column that has custom render method searchable, you should specify the field for it

**Comment by mbrn** [comment]
If you have any trouble or requirement please feel comfort to ask me?

**Comment by SilviaJoyceBalraj** [comment]
@mbrn Hi, The Search works fine for this one.

 <MaterialTable
          columns={[
            { title: 'Name', field: 'firstname', type: 'string' }
          ]}
/>
However Search filter does not work for the below code:

<MaterialTable
          columns={[
             { title: 'Name',
             field: 'firstname,
               render: rowData =>{ 
                       return(<Link to = {`/${rowData.firstname}`}> 
                       {rowData.firstname} 
                       </Link>)
               },
               type: 'string'
              }
            ]}
/>

Could you please help me with render search.
Thanks

**Comment by sarates** [comment]
@mbrn how I can make custom rendered field searchable?

**Comment by mbrn** [comment]
@sarates ,

Add customFilterAndSearch field to your column definition. 

```javascript
customFilterAndSearch: (value, rowData) => {
   return true; // customize here according your search algorithm.
}
```

**Comment by sarates** [comment]
@mbrn thanks a lot!

**Comment by Prasad-YS** [comment]
@mbrn Can you please insert some example code of  customFilterAndSearch, I'm not understanding how to use this function

**Comment by mbrn** [comment]
Hi @Prasad-YS ,

I think that would be enough for you

```
<MaterialTable
  columns={[
    {
      title: 'Name',
      render: rowData => rowData.name + ' ' + rowData.surname,
      customFilterAndSearch: (term, rowData) => (rowData.name + ' ' + rowData.surname).indexOf(term) != -1
    },
    { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
    {
      title: 'Birth Place',
      field: 'birthCity',
      lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
    }
  ]}
  data={[
    {
      name: 'Mehmet',
      surname: 'Baran',
      birthYear: 1987,
      birthCity: 63
    },
    {
      name: 'Zerya Betül',
      surname: 'Baran',
      birthYear: 2017,
      birthCity: 34
    },
  ]}
  title="Custom Render"
/>
```

**Comment by Prasad-YS** [comment]
> Hi @Prasad-YS ,
> 
> I think that would be enough for you
> 
> ```
> <MaterialTable
>   columns={[
>     {
>       title: 'Name',
>       render: rowData => rowData.name + ' ' + rowData.surname,
>       customFilterAndSearch: (term, rowData) => (rowData.name + ' ' + rowData.surname).indexOf(term) != -1
>     },
>     { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
>     {
>       title: 'Birth Place',
>       field: 'birthCity',
>       lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
>     }
>   ]}
>   data={[
>     {
>       name: 'Mehmet',
>       surname: 'Baran',
>       birthYear: 1987,
>       birthCity: 63
>     },
>     {
>       name: 'Zerya Betül',
>       surname: 'Baran',
>       birthYear: 2017,
>       birthCity: 34
>     },
>   ]}
>   title="Custom Render"
> />
> ```

Thanks a lot

**Comment by orestes22** [comment]
I know it is close this, but I need Help
 the filter box dont appear for me if I dont write field:
so I dont understand how you can made a filter with this customFilterAndSearch if the box dont appear

Best Regards

**Comment by mbrn** [comment]
You are right @orestes22 

It is a bug. I fixed it. I will publish it asap.

**Comment by orestes22** [comment]
Still not working. If you dont have Field with something between "" , it isnt works. 

Also I would like add in the Filter a Selection of checkbox with the option that appear in the colums. Can I implement that in the customFilterAndSearch ?

Best Regards

**Comment by mbrn** [comment]
you should have field or customFilterAndSearch in column definition. Can you check it again please?

**Comment by orestes22** [comment]
In your example works , but in my code doesnt, Im not sure why, because I check your code and you only have and "if" for show or not show that. but this is a minor things.

What comment do you have for this:
I would like add in the Filter a Selection of checkbox. Can I implement that in the customFilterAndSearch ?

**Comment by orestes22** [comment]
I would like that people choose the word and after that I will filter using that

**Comment by mbrn** [comment]
You can do this by customFilterAndSearch .

**Comment by anabeatrizzz** [comment]
@mbrn what is the solution for grouping columns with custom render? (Already reported [here](https://github.com/mbrn/material-table/issues/466#issue-433038099))

**Comment by anabeatrizzz** [comment]
@mbrn Your code is not working for me, returning `false` but table register is still showing:

```javascript
{
  // ...
  render: (rowData: any) => (
      <RenderComponent entity="user" entityId={rowData.userId} />
    ),
    customFilterAndSearch: async (filter, rowData) => {
      const users: User[] = await getUser().then((response: User) => response)
      const user = users.find((user: User) => user._id === rowData.userId)
      const userName = user.name.toLowerCase()
      const userFound = (userName.indexOf(filter.toLowerCase()) !== -1)
      console.log(userFound)
      return userFound
    },
}
```

**Comment by AndreasElgaard** [comment]
Hi @mbrn, 

Your solution works great, but now the search function is case-sensitive. Is there a way to disable? 


> Hi @Prasad-YS ,
> 
> I think that would be enough for you
> 
> ```
> <MaterialTable
>   columns={[
>     {
>       title: 'Name',
>       render: rowData => rowData.name + ' ' + rowData.surname,
>       customFilterAndSearch: (term, rowData) => (rowData.name + ' ' + rowData.surname).indexOf(term) != -1
>     },
>     { title: 'Birth Year', field: 'birthYear', type: 'numeric' },
>     {
>       title: 'Birth Place',
>       field: 'birthCity',
>       lookup: { 34: 'İstanbul', 63: 'Şanlıurfa' },
>     }
>   ]}
>   data={[
>     {
>       name: 'Mehmet',
>       surname: 'Baran',
>       birthYear: 1987,
>       birthCity: 63
>     },
>     {
>       name: 'Zerya Betül',
>       surname: 'Baran',
>       birthYear: 2017,
>       birthCity: 34
>     },
>   ]}
>   title="Custom Render"
> />
> ```
