### ISSUE TITLE
Search functionality broken by pagination

### ISSUE THREAD

**Issue by makr11** [mbrn/material-table#750]
If I search for an item on page X (e.g. 32) and number of items are below page 32, pagination is left on page 32 and warning is shown (Warning: Failed prop type: Material-UI: the page prop of a TablePagination is out of range (0 to 6, but page is 32)).

![paginationBug](https://user-images.githubusercontent.com/31960173/60014420-45f2d300-9681-11e9-8a9e-bf50bcdfe8fc.png)

**Comment by gianlucamateo** [comment]
should be resolved by PR #754

**Comment by vinterdo** [comment]
Issue is still present on version 1.45.0. Same steps to reproduce as described above.

Additionaly, it causes Invariant Violation: Maximum update depth exceeded later:
`
in the <span> component:
    in span (created by Tooltip)
    in Tooltip (created by WithStyles(Tooltip))
    in WithStyles(Tooltip) (created by MTablePaginationInner)
    in div (created by MTablePaginationInner)
    in MTablePaginationInner (created by WithStyles(MTablePaginationInner))
    in WithStyles(MTablePaginationInner) (created by ActionsComponent)
    in ActionsComponent (created by ForwardRef(TablePagination))
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (created by ForwardRef(TablePagination))
    in td (created by ForwardRef(TableCell))
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    in WithStyles(ForwardRef(TableCell)) (created by ForwardRef(TablePagination))
    in ForwardRef(TablePagination) (created by WithStyles(ForwardRef(TablePagination)))
    in WithStyles(ForwardRef(TablePagination)) (created by MaterialTable)
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
    in WithStyles(ForwardRef(TableRow)) (created by MaterialTable)
    in tfoot (created by ForwardRef(TableFooter))
    in ForwardRef(TableFooter) (created by WithStyles(ForwardRef(TableFooter)))
    in WithStyles(ForwardRef(TableFooter)) (created by MaterialTable)
    in table (created by ForwardRef(Table))
    in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
    in WithStyles(ForwardRef(Table)) (created by MaterialTable)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Container)
    in Container (created by MaterialTable)
    in Provider (created by App)
    in App (created by ErrorBoundary)
    in ErrorBoundary (created by DragDropContext)
    in DragDropContext (created by MaterialTable)
    in MaterialTable
    in Unknown (created by WithStyles(Component))
    in WithStyles(Component) (at PlacementsTable.tsx:69)
    in PlacementsTable (created by Context.Consumer)
   ...
`

**Comment by vinterdo** [comment]
Resolved in 1.47.0, can be closed
